### PR TITLE
v0.9 beta work

### LINKED ISSUE #36: Add ColorProvider
Have this ready on a private branch to push up, just need to rebase on new master.

### LINKED ISSUE #42: Clean-up CssStyleBroker to automatically track requires styles
This can also optimize calls to DeltaDecorations as we would know if we have to reset the styles or not instead of doing it each and every time!

### PR DESCRIPTION
**Pull request by hawkerm**
Just staging a comparison for myself on changes I want to finish for the v0.9 beta in the [0.9 milestone](https://github.com/hawkerm/monaco-editor-uwp/milestone/1).

To do:
- [x] #34 TypedocConverter script
- [x] #38 CodeLens Provider
- [x] #39 CodeAction Provider
- [x] #40 Add FindMatches Support

Work done:
- Fixes #36 Adds ColorProvider support
- Clean-up Language usage by adding shortcut on editor
- Fixes #42 Cleans-up CssStyleBroker inner workings (auto-tracks editors, optimizes and only updates WebView styles when needed, removes previously breaking change, probably should be tested more with more than one CodeEditor instance...)
- Fixes Library NuGet package Layout
- Clean-up ts/js file relation in solution
- Update readme/changelog

### CODE REVIEW

**Comment by hawkerm** [comment]
Actually was just thinking if we should make this the v0.20 release? As 1) it's 2020, and 2) that's the same version of Monaco it's based off of v0.20.0? Hmm...

**Comment by hez2010** [comment]
Ping. Any updates?

**Comment by hawkerm** [comment]
@hez2010 sorry time's disappeared on my weekends lately, work's been pretty busy. I'll try and dig into this more in a week or two and get something together.

**Comment by hawkerm** [comment]
Alright, almost have the Code Action provider working! 🎉🎉🎉

I have all the code setup locally now to support it using a `Command`; however, having it insert a `TextEdit` isn't working yet. Don't think I'm formatting something right between the JS/C#/JSON conversion, possibly with the Model URI needed by the TextEdit structure (which we haven't needed before).

**Comment by hawkerm** [comment]
Was able to test a packaged version too in Release mode, think things are working alright.

**Comment by hawkerm** [comment]
Alright, I think getting `CodeAction` working was finally the last feature I wanted to implement at the time. That was a tough one, finally got all the pieces working though. Had to add a polyfill for the Shadow DOM, fix an issue with Commands, make sure to add `dispose` method to returned objects, as well as figuring out how to attach `model.uri`, and finally debug a serialization issue with the `modelVersionId`...!

There's some remaining issues to resolve. I also noticed in Release mode, with Decoration Highlights, I seem to be getting a marshalling exception that I'm not getting when running in Debug mode... Need to investigate.

**Comment by hez2010** [comment]
I'm considering how about compiling monaco-editor manually to a lower target which is compatible with the old UWP WebView (maybe some polyfills are needed) so that we can use the latest monaco editor?

**Comment by hawkerm** [comment]
@hez2010 bit confused, this is still using the EdgeHTML WebView, what is your scenario you're needing?

I've already added one polyfill for shadow-dom needed for the version that was supposed to still work on EdgeHTML (but they added an incompatible feature). Though I don't know about future versions and adding more.

My plan is to release this update that works on WebView still after [investigating these 3 remaining bugs](https://github.com/hawkerm/monaco-editor-uwp/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.9-beta). Then I want to investigate generating the interfaces to a core .NET Standard lib and targeting WebView2 across different frameworks for a 'runtime' Make it easier to write code that works on top of the Monaco APIs but can then be run by multiple types of applications. I'm starting to investigate and experiment at least in parallel on this next week.

It'd be great if we could coordinate efforts to move things forward.

**Comment by hez2010** [comment]
Never mind, that was just a thought about what kind of work is needed post v0.9 (before WebView2 becomes available for UWP). 

> My plan is to release this update that works on WebView still after investigating these 3 remaining bugs. Then I want to investigate generating the interfaces to a core .NET Standard lib and targeting WebView2 across different frameworks for a 'runtime' Make it easier to write code that works on top of the Monaco APIs but can then be run by multiple types of applications. I'm starting to investigate and experiment at least in parallel on this next week.

Sounds great.

**Comment by hawkerm** [comment]
@hez2010 cool, I also misunderstood that you were talking about monaco itself. 🙂 Agree that hopefully moving to WebView2 should be the next step and unlock us following the latest Monaco development too. 🙂

**Comment by hawkerm** [comment]
Alright, think we're finally all set! 🤞

Too late now, but next time I sit down at this again in the next day or two, I'll kick-off a full build to get a package and do a final test with those bits. Then we can merge this to main and upload to NuGet... 🚀

**Pull request merged**
